/**
 * One-time interactive Google sign-in helper.
 *
 * Usage:
 *   npm run auth:login              — headful browser, wait for human login (5 min)
 *   GMAPS_AUTH_TEST=1 npm run auth:login — headless smoke test (extraction paths only)
 *
 * Writes GMAPS_COOKIES and GMAPS_AUTH_TOKEN to .env.local (merged, never overwrites other keys).
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { launchBrowser } from './lib/cdp.js';
import {
  attachPage,
  enablePageSession,
  evaluate,
  readWizTokens,
  setConsentCookies,
  sleep,
  waitForLoad,
} from './lib/maps-harness.js';

const ENV_FILE = join(process.cwd(), '.env.local');
const LOGIN_TIMEOUT_MS = 5 * 60 * 1000;
const POLL_MS = 2000;
const MAPS_URL = 'https://www.google.com/maps';
const SIGNIN_URL = 'https://accounts.google.com/signin/v2/identifier?service=local&continue=https%3A%2F%2Fwww.google.com%2Fmaps&flowName=GlifWebSignIn&flowEntry=ServiceLogin';

const GOOGLE_COOKIE_PREFIXES = [
  'SID',
  'HSID',
  'SSID',
  'APISID',
  'SAPISID',
  'NID',
  '__Secure-1PSID',
  '__Secure-3PSID',
  '__Secure-1PAPISID',
  '__Secure-3PAPISID',
  '__Secure-1PSIDTS',
  '__Secure-3PSIDTS',
  '__Secure-1PSIDCC',
  '__Secure-3PSIDCC',
];

interface CdpCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  secure?: boolean;
  httpOnly?: boolean;
}

function isGoogleRelevantCookie(name: string): boolean {
  if (GOOGLE_COOKIE_PREFIXES.includes(name)) return true;
  if (name.startsWith('__Secure-')) return true;
  return false;
}

function formatCookieHeader(cookies: CdpCookie[]): string {
  const byName = new Map<string, string>();
  for (const cookie of cookies) {
    if (!cookie.domain.includes('google')) continue;
    if (!isGoogleRelevantCookie(cookie.name)) continue;
    byName.set(cookie.name, cookie.value);
  }
  return [...byName.entries()].map(([name, value]) => `${name}=${value}`).join('; ');
}

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

function serializeEnvFile(map: Map<string, string>): string {
  const lines: string[] = [
    '# Generated by npm run auth:login — do not commit',
    `# Updated: ${new Date().toISOString()}`,
    '',
  ];
  const order = ['GMAPS_COOKIES', 'GMAPS_AUTH_TOKEN'];
  const written = new Set<string>();
  for (const key of order) {
    const value = map.get(key);
    if (value != null) {
      lines.push(`${key}=${value}`);
      written.add(key);
    }
  }
  for (const [key, value] of map) {
    if (written.has(key)) continue;
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

function mergeEnvFile(cookies: string, authToken: string): { cookieNames: string[]; hadToken: boolean } {
  const existing = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf8') : '';
  const map = existing ? parseEnvFile(existing) : new Map<string, string>();
  map.set('GMAPS_COOKIES', cookies);
  map.set('GMAPS_AUTH_TOKEN', authToken);
  writeFileSync(ENV_FILE, serializeEnvFile(map));

  const cookieNames = cookies
    .split(';')
    .map((part) => part.trim().split('=')[0] ?? '')
    .filter(Boolean);
  return { cookieNames, hadToken: authToken.length > 0 };
}

async function detectSignedIn(page: { connection: import('./lib/cdp.js').CdpConnection; sessionId: string }): Promise<boolean> {
  const href = await evaluate<string>(page, 'location.href');
  if (!href?.includes('google.com/maps')) return false;

  const signedIn = await evaluate<boolean>(
    page,
    `(() => {
      const wiz = window.WIZ_global_data || {};
      if (wiz.SNlM0e) return true;
      const avatar = document.querySelector('[aria-label*="Google Account"], img[src*="googleusercontent.com/a/"], [data-value="Sign in"]');
      if (!avatar) return false;
      const label = (avatar.getAttribute('aria-label') || avatar.getAttribute('data-value') || '').trim();
      if (/sign in/i.test(label)) return false;
      if (avatar.matches('[aria-label*="Google Account"], img[src*="googleusercontent.com/a/"]')) return true;
      return false;
    })()`,
  );
  return signedIn === true;
}

async function extractSession(page: { connection: import('./lib/cdp.js').CdpConnection; sessionId: string }): Promise<{
  cookies: string;
  cookieNames: string[];
  authToken: string;
}> {
  await page.connection.send('Network.enable', {}, page.sessionId);
  const result = await page.connection.send('Network.getAllCookies', {}, page.sessionId);
  const allCookies = (result.cookies as CdpCookie[] | undefined) ?? [];
  const cookieHeader = formatCookieHeader(allCookies);
  const cookieNames = cookieHeader
    .split(';')
    .map((part) => part.trim().split('=')[0] ?? '')
    .filter(Boolean);

  const tokens = await readWizTokens(page);
  const authToken = tokens.SNlM0e ?? '';

  return { cookies: cookieHeader, cookieNames, authToken };
}

async function runHeadlessSmokeTest(): Promise<void> {
  console.log('GMAPS_AUTH_TEST=1 — headless smoke test (no login, extraction paths only)\n');
  const browser = await launchBrowser({ headless: true });
  try {
    const sessionId = await attachPage(browser.connection);
    const page = { connection: browser.connection, sessionId };
    await enablePageSession(page);

    console.log('Navigating to Google sign-in page...');
    await browser.connection.send('Page.navigate', { url: SIGNIN_URL }, sessionId);
    await waitForLoad(page, 45_000).catch(() => undefined);
    await sleep(3000);

    const href = await evaluate<string>(page, 'location.href');
    const onSignIn =
      Boolean(href?.includes('accounts.google.com')) || Boolean(href?.includes('ServiceLogin'));
    if (!onSignIn) {
      throw new Error(`Expected sign-in page, got: ${href ?? '(unknown)'}`);
    }
    console.log('OK: reached Google sign-in page');

    console.log('Navigating to Maps (anonymous) for token extraction...');
    await browser.connection.send('Page.navigate', { url: MAPS_URL }, sessionId);
    await waitForLoad(page, 45_000).catch(() => undefined);
    await sleep(5000);

    const { cookies, cookieNames, authToken } = await extractSession(page);
    console.log(`OK: extracted ${cookieNames.length} cookie name(s): ${cookieNames.join(', ') || '(none)'}`);
    console.log(`OK: SNlM0e token ${authToken ? 'present' : 'empty (expected for anonymous)'}`);

    if (authToken.length > 0) {
      console.warn('WARN: anonymous Maps session had SNlM0e — may be a headless artifact');
    }

    const tmpEnv = join(process.cwd(), '.cache', 'probes', 'auth-login-smoke.env');
    writeFileSync(
      tmpEnv,
      serializeEnvFile(new Map([
        ['GMAPS_COOKIES', cookies],
        ['GMAPS_AUTH_TOKEN', authToken],
      ])),
    );
    console.log(`Smoke artifact: ${tmpEnv}`);
    console.log(`Cookie names captured: ${cookieNames.join(', ') || '(none)'}`);
    console.log('\nHeadless smoke test passed.');
  } finally {
    await browser.close();
  }
}

async function runInteractiveLogin(): Promise<void> {
  console.log(`
╔══════════════════════════════════════════════════════════════════╗
║  Google Maps login helper                                        ║
╠══════════════════════════════════════════════════════════════════╣
║  A Chrome window will open. Sign in with your Google account     ║
║  (including 2FA if prompted).                                    ║
║                                                                  ║
║  After sign-in completes, you will be redirected to Maps.        ║
║  This script detects that and saves cookies to .env.local.       ║
║                                                                  ║
║  Timeout: ${Math.round(LOGIN_TIMEOUT_MS / 60_000)} minutes                                              ║
╚══════════════════════════════════════════════════════════════════╝
`);

  const browser = await launchBrowser({ headless: false });
  try {
    const sessionId = await attachPage(browser.connection);
    const page = { connection: browser.connection, sessionId };
    await enablePageSession(page);

    console.log('Opening Google sign-in...');
    await browser.connection.send('Page.navigate', { url: SIGNIN_URL }, sessionId);
    await waitForLoad(page, 45_000).catch(() => undefined);

    const deadline = Date.now() + LOGIN_TIMEOUT_MS;
    let signedIn = false;

    while (Date.now() < deadline) {
      await sleep(POLL_MS);
      const href = await evaluate<string>(page, 'location.href');

      if (href && !href.includes('google.com/maps') && !href.includes('accounts.google.com')) {
        console.log('Navigating to Maps to confirm session...');
        await browser.connection.send('Page.navigate', { url: MAPS_URL }, sessionId);
        await sleep(4000);
      }

      if (await detectSignedIn(page)) {
        signedIn = true;
        break;
      }

      const remaining = Math.ceil((deadline - Date.now()) / 1000);
      if (remaining % 30 === 0 || remaining <= 10) {
        process.stdout.write(`\rWaiting for sign-in... ${remaining}s remaining   `);
      }
    }

    console.log('');

    if (!signedIn) {
      console.error(`
Login timed out after ${Math.round(LOGIN_TIMEOUT_MS / 60_000)} minutes.
Complete sign-in in the browser window and run \`npm run auth:login\` again.
`);
      process.exit(1);
    }

    console.log('Sign-in detected. Extracting session...');
    await sleep(2000);
    await browser.connection.send('Page.navigate', { url: MAPS_URL }, sessionId);
    await sleep(5000);

    const { cookies, cookieNames, authToken } = await extractSession(page);
    if (cookieNames.length === 0) {
      console.error('No Google cookies captured — sign-in may not have completed fully.');
      process.exit(1);
    }

    const { cookieNames: written, hadToken } = mergeEnvFile(cookies, authToken);
    console.log(`
Saved to .env.local:
  Cookie names (${written.length}): ${written.join(', ')}
  GMAPS_AUTH_TOKEN (SNlM0e): ${hadToken ? 'present' : 'empty — legacy batchexecute may stay blocked'}

Values are NOT printed here. Restart your SDK scripts to pick up the new env.
`);
  } finally {
    await browser.close();
  }
}

async function main(): Promise<void> {
  if (process.env.GMAPS_AUTH_TEST === '1') {
    await runHeadlessSmokeTest();
    return;
  }
  await runInteractiveLogin();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
